openapi: 3.0.0
info:
  title: Books API
  version: '1.0'
servers:
  - url: http://localhost:5000/api
paths:
  /books:
    get:
      summary: Get all students
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
  /students/{id}:
    get:
      summary: Get student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    put:
      summary: Update student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    delete:
      summary: Delete student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the student to delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        book_name:
          type: string
        author_name:
          type: string
        write_date:
          type: integer
          format: int32
        janre:
          type: integer
          format: int32
      required:
        - book_name
        - author_name
        - write_date
        - janre

